version: 2.0

jobs:
  build:
    working_directory: ~/dynamic-rest
    parallelism: 1

    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      # - run:
      #     name: Update PATH variable
      #     command: echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> ${BASH_ENV}
      - run:
          name: Install from requirements.txt
          # command: pip install -r requirements.txt
          command: pip install --user --exists-action w -r requirements.txt
      - run:
          name: Run Setup
          command: python setup.py develop --user
      - run:
          name: Run Integration tests
          command: ENABLE_INTEGRATION_TESTS=True py.test tests/integration

# workflows:
#   version: 2
#   build-and-test:
#     jobs:
#       - build:
#           context: org-global
